# Generated by Django 4.2.7 on 2023-12-03 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ibnuaqilcart', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaksi',
            name='alamat',
        ),
        migrations.RemoveField(
            model_name='transaksi',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='transaksi',
            name='email',
        ),
        migrations.RemoveField(
            model_name='transaksi',
            name='kabupaten',
        ),
        migrations.RemoveField(
            model_name='transaksi',
            name='kecamatan',
        ),
        migrations.RemoveField(
            model_name='transaksi',
            name='kode_post',
        ),
        migrations.RemoveField(
            model_name='transaksi',
            name='nama_belakang',
        ),
        migrations.RemoveField(
            model_name='transaksi',
            name='nama_depan',
        ),
        migrations.RemoveField(
            model_name='transaksi',
            name='no_transaksi',
        ),
        migrations.RemoveField(
            model_name='transaksi',
            name='provinsi',
        ),
        migrations.RemoveField(
            model_name='transaksi',
            name='status',
        ),
        migrations.RemoveField(
            model_name='transaksi',
            name='tanggal_kirim',
        ),
        migrations.RemoveField(
            model_name='transaksi',
            name='total_transaksi',
        ),
        migrations.RemoveField(
            model_name='transaksi',
            name='whatsapp',
        ),
    ]
