# Generated by Django 4.2.7 on 2023-11-30 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AQIL', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produk',
            name='gambar_dua',
            field=models.ImageField(blank=True, null=True, upload_to='gambar/banner'),
        ),
        migrations.AlterField(
            model_name='produk',
            name='gambar_empat',
            field=models.ImageField(blank=True, null=True, upload_to='gambar/banner'),
        ),
        migrations.AlterField(
            model_name='produk',
            name='gambar_lima',
            field=models.ImageField(blank=True, null=True, upload_to='gambar/banner'),
        ),
        migrations.AlterField(
            model_name='produk',
            name='gambar_satu',
            field=models.ImageField(blank=True, null=True, upload_to='gambar/banner'),
        ),
        migrations.AlterField(
            model_name='produk',
            name='gambar_tiga',
            field=models.ImageField(blank=True, null=True, upload_to='gambar/banner'),
        ),
    ]
