# Generated by Django 4.2.7 on 2024-01-16 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AQIL', '0003_alter_kategori_options_alter_kontak_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='produk',
            options={'verbose_name_plural': 'Data Produk'},
        ),
    ]
